title: lsfont
author: Minseo Lee
email: itoupluk427@gmail.com
# description:
url: https://lsfont.quiple.dev
twitter_username: kuipuru
github_username: quiple
github_reponame: lsfont
sass:
  style: compressed
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - lsfont.html